### ISSUE TITLE
Zephyr and Contiki binaries containing all bugs

### ISSUE THREAD

**Issue by guyf2010** [fuzzware-fuzzer/fuzzware-experiments#1]
I see from the readme that the binaries for the fuzzing new targets section have been separated out by CVE, but it's also noted that some of the bugs take longer to find given the extra validation from the applied patches.

I'm interested in testing the original binaries used to originally identify all of the bugs. I looked at removing the patches from the build scripts, but noticed the BASE_COMMIT value varies between some of these scripts as well. It is possible to have precompiled binaries or build scripts added to reproduce the original tests?

Thanks

**Comment by Scepticz** [comment]
The base commit varies for Zephyr as we fuzzed at two different points. You can see the two big chunks from CVE numbers (2020 and 2021/2022). I would recommend building two binaries for the Zephyr CVEs, one for the 2020 CVEs and the other for the 2021/2022 CVEs. Within these, the small commit differences should only be for technical patching reasons
