### ISSUE TITLE
P2IM & uEmu

### ISSUE THREAD

**Issue by dingiso** [fuzzware-fuzzer/fuzzware-experiments#2]

**Comment by dingiso** [comment]
Hi Scepticz,

I'm interested in the P2IM and uEmu experiments results, but I have not found them in the repo. 

May you offer the final output `config.yml` of the experiments? Thanks

Dingiso

**Comment by Scepticz** [comment]
Hi dingiso,

you can find the config.yml configuration files for running the experiments in the respective target directories. For example, see https://github.com/fuzzware-fuzzer/fuzzware-experiments/blob/main/02-comparison-with-state-of-the-art/P2IM/CNC/config.yml.

Using these, you can reproduce the results on your own hardware in case you would like to create a valid, direct comparison. For our own results, you can also have a look at the paper.

Best
Tobi

**Comment by dingiso** [comment]
Hi sceptic
May I get your own results `config.yml` files for comparison ? 

Best
dingiso

**Comment by Scepticz** [comment]
There is no result `config.yml` which is generated by the experiment. I think you are misunderstanding the output of the experiments. If you give me more information about your situation, I might be able to be of more help

**Comment by Scepticz** [comment]
Thinking about this more, there are of course model configurations which are generated while running the fuzzer. If you let me know what exact information you are looking for, maybe this allows me to be of help

**Comment by dingiso** [comment]
Hi Scepticz,

I want to get the mmio models generated by the experiments like what has been used in `03-fuzzing-new-targets` dir. 

I am doing this experiment on my pc as well, but considering my PC is a little old, it takes bunch of time even using the parallel method. So I think the easiest and fastest way is to ask for the model files.I want the models for two reasons. 

- First I am more familiar with the p2im and uEmu, so I want to read the mmio models to better understand the fuzzware.

- Second is to make a comparison with the results of my experiments.

Thanks for you to answer carefully

Thanks
dingiso

**Comment by Scepticz** [comment]
Generating the models usually does not take a lot of time into the experiment. To generate the models, you also do not need to re-run the fuzzer for every target multiple times. What you can basically use is the `fuzzware pipeline --run-for=01:00` command and then get the `mmio_config.yml` file which contains the MMIO models. You can also achieve this by setting the experiment repetition count to 1, the time per experiment to 1 hour, .... and then using the original eval scripts

**Comment by dingiso** [comment]
ok thanks
